### ISSUE TITLE
Caddy start does not work

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/prefab9#120]
#### Installation information

- jumpscale version: master
- operating system: docker

#### Detailed description
Starting caddy sever does not work due using the wrong API of the process manager

#### Steps to reproduce
Execute: j.tools.prefab.local.web.caddy.start()

#### Relevant stacktraces
Traceback (most recent call last):
  File "/usr/local/bin/js9", line 21, in <module>
    exec(toexec)
  File "<string>", line 1, in <module>
  File "/opt/code/github/jumpscale/prefab9/modules/web/PrefabCaddy.py", line 153, in start
    self.prefab.system.processmanager.stop("caddy")  # will also kill
AttributeError: 'PrefabProcessManager' object has no attribute 'stop'
'PrefabProcessManager' object has no attribute 'stop'

**Comment by ahussein** [comment]
blocking https://github.com/zero-os/0-orchestrator/issues/1370
