### ISSUE TITLE
ImportError: No module named 'JumpScale9Lib'

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#178]
#### Installation information

- jumpscale version: 9.2.1
- operating system: Ubuntu 16.04 (ch-gen-1)

Also see: https://github.com/Jumpscale/prefab9/issues/177

Difference with #177 is that the below was executed on completely new VM, with `export ZUTILSBRANCH=9.2.1` (instead of `export ZUTILSBRANCH=master`)

#### Detailed description

Creating an AYS Server image using `ZInstall_ays9` fails.

#### Steps to reproduce

```bash
export ZUTILSBRANCH=9.2.1
curl https://raw.githubusercontent.com/Jumpscale/bash/${ZUTILSBRANCH}/install.sh?$RANDOM > /tmp/install.sh
bash /tmp/install.sh
. ~/.bash_profile
export JS9BRANCH=9.2.1
ZInstall_ays9
``

#### Relevant stacktraces

```python
[+] installing jumpscale ays9
Traceback (most recent call last):
  File "/usr/local/bin/js9", line 20, in <module>
    exec(toexec)
  File "<string>", line 1, in <module>
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabFactory.py", line 20, in local
    self._local = self.get(j.tools.executorLocal)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabFactory.py", line 85, in get
    self.loader.load(executor,prefab)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabLoader.py", line 102, in load
    exec("from %s import %s" % (basename, basename))
  File "<string>", line 1, in <module>
  File "/opt/code/github/jumpscale/prefab9/modules/network/PrefabDNSMasq.py", line 5, in <module>
    from JumpScale9Lib.sal.dnsmasq.Dnsmasq import DNSMasq
ImportError: No module named 'JumpScale9Lib'

**** ERRORLOG ****
FUNCTION: ZCodeGet
mkdir: /opt/code/github/jumpscale
pushd to: /opt/code/github/jumpscale
/opt/code/github/jumpscale ~
github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==


FUNCTION: container
FUNCTION: ZDockerConfig

mkdir: /root/js9host//.cache/pip
mkdir: /root/js9host//cfg
No module named 'JumpScale9Lib'

[-] something went wrong: could not ssh command: cd  /opt/code/github/jumpscale/ays9 && bash install.sh;
```

**Comment by rkhamis** [comment]
should be fixed in https://github.com/Jumpscale/lib9/commit/257146b7db7776107e8187ea9f72b92626829998

**Comment by yveskerwyn** [comment]
verified
