### ISSUE TITLE
can't install mattermost bot using prefab 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [Jumpscale/prefab9#195]
#### Installation information

- jumpscale version:
- operating system:

#### Steps to reproduce

prefab.apps.mattermostbot.install('<bot_username>', '<bot_email>', '<bot_password>')

#### Relevant stacktraces
```
RuntimeError: ERROR: Could not execute cmd:export PYTHONPATH="/opt/code/mattermost_bot" && export MATTERMOST_BOT_SETTINGS_MODULE="local_settings" && cd /opt/code/mattermost_bot && matterbot
Out/Err:
**START**
Traceback (most recent call last):
  File "/usr/local/bin/matterbot", line 9, in <module>
    load_entry_point('mattermost-bot==1.0.20', 'console_scripts', 'matterbot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/mattermost_bot-1.0.20-py3.5.egg/mattermost_bot/cli.py", line 5, in <module>
    from mattermost_bot import bot, settings
  File "/usr/local/lib/python3.5/dist-packages/mattermost_bot-1.0.20-py3.5.egg/mattermost_bot/bot.py", line 15, in <module>
    from mattermost_bot import settings
  File "/usr/local/lib/python3.5/dist-packages/mattermost_bot-1.0.20-py3.5.egg/mattermost_bot/settings.py", line 46, in <module>
    settings = importlib.import_module(settings_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/code/mattermost_bot/local_settings.py", line 2
    BOT_URL = http://localhost:8059/api/v4
                  ^
SyntaxError: invalid syntax

root@vm-826:/opt/code/mattermost_bot#

 ((type:runtime.error)

```

**Comment by arahmanhamdy** [comment]
Fixed https://github.com/Jumpscale/prefab9/commit/a5c14ab24015040841a0efc4966c4d0136a1f136
