### ISSUE TITLE
Installing core9 using prefab fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#66]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu 16.04

#### Steps to reproduce
```python
...
prefab = vm.prefab
prefab.js9.js9core.install()
```

#### Relevant stacktraces

```bash
Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -     configsave
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -     configsave
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -     initenv done on executor base
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -     Traceback (most recent call last):
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "<string>", line 1, in <module>
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/opt/code/github/jumpscale/core9/setup.py", line 97, in <module>
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         'cmds/js9_docs',
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         dist.run_commands()
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         self.run_command(cmd)
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         cmd_obj.run()
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/opt/code/github/jumpscale/core9/setup.py", line 42, in run
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         self.execute(_post_install, (libname, libpath), msg="Running post install task")
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/usr/lib/python3.5/distutils/cmd.py", line 336, in execute
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         util.execute(func, args, msg, dry_run=self.dry_run)
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/usr/lib/python3.5/distutils/util.py", line 301, in execute
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         func(*args)
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/opt/code/github/jumpscale/core9/setup.py", line 23, in _post_install
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         j.tools.jsloader.generate()
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -       File "/opt/code/github/jumpscale/core9/JumpScale9/tools/loader/JSLoader.py", line 442, in generate
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -         for name, path in j.application.config['plugins'].items():
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -     KeyError: 'plugins'
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -     'plugins'
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -     ----------------------------------------
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     - Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/code/github/jumpscale/core9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/code/github/jumpscale/core9/
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     - [-] something went wrong: Could not install core9 of js9
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -
[Mon06 16:37] - SSHClient.py        :260 :j.ssh sync client: 195.143.34.181(2201): - INFO     -
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 prefab.js9.js9core.install()

/opt/code/github/jumpscale/prefab9/modules/js9/Prefabjs9Core.py in install(self, reset)
     29         self.logger.info("js9_install")
     30         self.core.run(
---> 31             "export JS9BRANCH='9.3.0';ZInstall_host_js9", profile=True)
     32
     33         self.prefab.runtimes.pip.install("Cython,asyncssh,numpy,tarantool")

/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py in run(self, cmd, die, debug, checkok, showout, profile, replaceArgs, shell, env, timeout)
   1154
   1155         rc, out, err = self.executor.execute(
-> 1156             cmd, checkok=checkok, die=die, showout=showout, env=env, timeout=timeout)
   1157
   1158         # out = self._clean(out)

/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py in execute(self, cmds, die, checkok, showout, timeout, env, asScript, hide)
    130
    131         rc, out, err = self.sshclient.execute(
--> 132             cmds2, die=die, showout=showout)
    133
    134         if hide is False:

/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py in execute(self, cmd, showout, die)
    287         if rc and die:
    288             raise j.exceptions.RuntimeError(
--> 289                 "Cannot execute (ssh):\n%s\noutput:\n%serrors:\n%s" % (cmd, out.getvalue(), err.getvalue()))
    290
    291         return rc, out.getvalue(), err.getvalue()

RuntimeError: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;export JS9BRANCH='9.3.0';ZInstall_host_js9"

````

...

```bash
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/code/github/jumpscale/core9/setup.py", line 97, in <module>
        'cmds/js9_docs',
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/code/github/jumpscale/core9/setup.py", line 42, in run
        self.execute(_post_install, (libname, libpath), msg="Running post install task")
      File "/usr/lib/python3.5/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/util.py", line 301, in execute
        func(*args)
      File "/opt/code/github/jumpscale/core9/setup.py", line 23, in _post_install
        j.tools.jsloader.generate()
      File "/opt/code/github/jumpscale/core9/JumpScale9/tools/loader/JSLoader.py", line 442, in generate
        for name, path in j.application.config['plugins'].items():
    KeyError: 'plugins'
    'plugins'

    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/code/github/jumpscale/core9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/code/github/jumpscale/core9/

[-] something went wrong: Could not install core9 of js9


errors:
 ((type:runtime.error)
```

**Comment by alichaddad** [comment]
Since accessing Jumpscale configuration has been changed, this is no longer an issue and it can't be reproduced.
