### ISSUE TITLE
prefab.web.portal.start() fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#88]
#### Installation information

- jumpscale version: master

#### Detailed description

After having started successfully a remote JumpScale Portal, updated the portal configuration and stopped the portal, as via prefab as below below, restarting the portal fails.

See: https://se-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1535

#### Steps to reproduce

```python
...
prefab = ays_server_93.prefab
prefab.web.portal.install(False)
prefab.web.portal.start()
prefab.web.portal.configure(mongodbip='127.0.0.1', mongoport=27017, production=True, client_id='ays-server-clients-org', client_secret=ays_clients_org_secret, organization='ays-portal-users')
prefab.web.portal.stop()
prefab.web.portal.start()
```

When checking the tmux session:

<img width="1027" alt="screen shot 2017-11-22 at 21 42 57" src="https://user-images.githubusercontent.com/13795109/33148990-33b0c0c4-cfce-11e7-8b15-ac3ae6680e4f.png">

#### Relevant stacktraces

```
**ERROR**
root@ays-server-93:/opt/jumpscale9/apps/portals/main# echo **START**;cd /opt/jumpscale9/apps/portals/main && python3 portal_start.py && echo **OK** || echo **ERROR**
**START**
Traceback (most recent call last):
  File "portal_start.py", line 42, in <module>
    cli(obj={})
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "portal_start.py", line 21, in cli
    start()
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "portal_start.py", line 36, in start
    server = j.portal.tools.server.get()
AttributeError: 'Portal' object has no attribute 'tools'
'Portal' object has no attribute 'tools'
**ERROR**
```

**Comment by khaledkbadr** [comment]
Can't reproduce with provided steps
